
services:
  master1:
    build: .
    container_name: master1
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    ports:
      - "2220:22"
    volumes:
      - shared_volume:/shared
      - ./ssh_keys:/root/.ssh # Mount pre-generated SSH keys for passwordless access
    tmpfs:
      - /shared:mode=777

  node1:
    build: .
    container_name: node1
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    ports:
      - "2221:22"
    volumes:
      - shared_volume:/shared
      - ./ssh_keys:/root/.ssh
    tmpfs:
      - /shared:mode=777
  node2:
    build: .
    container_name: node2
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    ports:
      - "2222:22"
    volumes:
      - shared_volume:/shared
      - ./ssh_keys:/root/.ssh
    tmpfs:
      - /shared:mode=777

networks:
  my_network:
    driver: bridge

volumes:
  shared_volume:
    driver: local