services:
  master:
    build: .
    container_name: Master
    hostname: Master
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    ports:
      - "2232:22"
    volumes:
      - shared_volume:/shared:mode=777
      - ./results:/shared/results
  
  node01:
    build: .
    container_name: Node01
    hostname: Node01
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    ports:
      - "2233:22"
    volumes:
      - shared_volume:/shared:mode=777
      - ./results:/shared/results

  node02:
    build: .
    container_name: Node02
    hostname: Node02
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    ports:
      - "2234:22"
    volumes:
      - shared_volume:/shared:mode=777
      - ./results:/shared/results

networks:
  my_network:
    driver: bridge

volumes:
  shared_volume:
    driver: local
